# Introduction to NumPy


#### 1. Import NumPy under the name np.

In [1]:
# your code here
import numpy as np

#### 2. Print your NumPy version.

In [2]:
# your code here
print(np.version.version)

1.18.1


#### 3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable *a*.
**Challenge**: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find?

In [3]:
# Method 1
a = np.random.randint(10, size = (2,3,5))


In [4]:
# Method 2
a = np.random.rand(2,3,5)

In [5]:
# Method 3
a = np.random.random((2,3,5))

#### 4. Print *a*.


In [6]:
# your code here
print(a)

[[[0.04791362 0.42763267 0.15589405 0.92237056 0.98887407]
  [0.1284238  0.60085761 0.6952631  0.53560008 0.30681469]
  [0.53558819 0.47931185 0.57281311 0.05579446 0.236033  ]]

 [[0.61208693 0.83011894 0.75321107 0.18940325 0.10735371]
  [0.10370821 0.83028052 0.63549879 0.09997061 0.02991578]
  [0.84650939 0.10459215 0.23316721 0.86143709 0.11110789]]]


#### 5. Create a 5x2x3 3-dimensional array with all values equaling 1. Assign the array to variable *b*.

In [7]:
# your code here
b = np.ones((5,2,3))

#### 6. Print *b*.


In [8]:
# your code here
print(b)

[[[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]]


#### 7. Do *a* and *b* have the same size? How do you prove that in Python code?

In [9]:
# your code here

print(a.size == b.size)

True


#### 8. Are you able to add *a* and *b*? Why or why not?


In [10]:
# your answer here
#They don't have the same shape. The shape of a is (3,2,3,5) while the shape of b is (3,5,2,3) but they have the smae size
print(a.shape == b.shape)

False


In [11]:
np.add(a, b)

ValueError: operands could not be broadcast together with shapes (2,3,5) (5,2,3) 

#### 9. Transpose *b* so that it has the same structure of *a* (i.e. become a 2x3x5 array). Assign the transposed array to variable *c*.

In [12]:
# your code here
print(a.shape, '-', b.shape)

(2, 3, 5) - (5, 2, 3)


In [15]:
c = np.transpose(b, [1, 2, 0])

In [19]:
print(a.shape, '-', c.shape)

#### 10. Try to add *a* and *c*. Now it should work. Assign the sum to variable *d*. But why does it work now?

In [20]:
# your code/answer here
#Two arrays have the same shape and size now
d = np.add(a,c)
print(d)

[[[1.04791362 1.42763267 1.15589405 1.92237056 1.98887407]
  [1.1284238  1.60085761 1.6952631  1.53560008 1.30681469]
  [1.53558819 1.47931185 1.57281311 1.05579446 1.236033  ]]

 [[1.61208693 1.83011894 1.75321107 1.18940325 1.10735371]
  [1.10370821 1.83028052 1.63549879 1.09997061 1.02991578]
  [1.84650939 1.10459215 1.23316721 1.86143709 1.11110789]]]


#### 11. Print *a* and *d*. Notice the difference and relation of the two array in terms of the values? Explain.

In [22]:
# your code/answer here
print("A",a)
print("D",d)
# d  result,we can see clearly that we add 1 to every elements of a 

A [[[0.04791362 0.42763267 0.15589405 0.92237056 0.98887407]
  [0.1284238  0.60085761 0.6952631  0.53560008 0.30681469]
  [0.53558819 0.47931185 0.57281311 0.05579446 0.236033  ]]

 [[0.61208693 0.83011894 0.75321107 0.18940325 0.10735371]
  [0.10370821 0.83028052 0.63549879 0.09997061 0.02991578]
  [0.84650939 0.10459215 0.23316721 0.86143709 0.11110789]]]
D [[[1.04791362 1.42763267 1.15589405 1.92237056 1.98887407]
  [1.1284238  1.60085761 1.6952631  1.53560008 1.30681469]
  [1.53558819 1.47931185 1.57281311 1.05579446 1.236033  ]]

 [[1.61208693 1.83011894 1.75321107 1.18940325 1.10735371]
  [1.10370821 1.83028052 1.63549879 1.09997061 1.02991578]
  [1.84650939 1.10459215 1.23316721 1.86143709 1.11110789]]]


#### 12. Multiply *a* and *c*. Assign the result to *e*.

In [23]:
# your code here
e = np.multiply(a,c)

#### 13. Does *e* equal to *a*? Why or why not?


In [24]:
# your code/answer here
print(a == e)

[[[ True  True  True  True  True]
  [ True  True  True  True  True]
  [ True  True  True  True  True]]

 [[ True  True  True  True  True]
  [ True  True  True  True  True]
  [ True  True  True  True  True]]]


#### 14. Identify the max, min, and mean values in *d*. Assign those values to variables *d_max*, *d_min* and *d_mean*.

In [25]:
# your code here
d_max = d.max()
d_min = d.min()
d_mean = d.mean()

#### 15. Now we want to label the values in *d*. First create an empty array *f* with the same shape (i.e. 2x3x5) as *d* using `np.empty`.


In [26]:
# your code here
print('MAX:  ', d_max)
print('MIN:  ', d_min)
print('MEAN: ', d_mean)

MAX:   1.9888740698907355
MIN:   1.0299157763948918
MEAN:  1.4345848806133326


#### 16. Populate the values in *f*. 

For each value in *d*, if it's larger than *d_min* but smaller than *d_mean*, assign 25 to the corresponding value in *f*. If a value in *d* is larger than *d_mean* but smaller than *d_max*, assign 75 to the corresponding value in *f*. If a value equals to *d_mean*, assign 50 to the corresponding value in *f*. Assign 0 to the corresponding value(s) in *f* for *d_min* in *d*. Assign 100 to the corresponding value(s) in *f* for *d_max* in *d*. In the end, f should have only the following values: 0, 25, 50, 75, and 100.

**Note**: you don't have to use Numpy in this question.

In [31]:
# your code here
f = np.empty((2, 3, 5), dtype=np.int8)

#### 17. Print *d* and *f*. Do you have your expected *f*?
For instance, if your *d* is:
```python
[[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],
[1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],
[1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],
[[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],
[1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
[1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]]
```
Your *f* should be:
```python
[[[ 75.,  75.,  75.,  25.,  75.],
[ 75.,  75.,  25.,  25.,  25.],
[ 75.,  25.,  75.,  75.,  75.]],
[[ 25.,  25.,  25.,  25., 100.],
[ 75.,  75.,  75.,  75.,  75.],
[ 25.,  75.,   0.,  75.,  75.]]]
```

In [30]:
# your code here
print('D');
print(d);
print('F');
print(f);

D
[[[1.04791362 1.42763267 1.15589405 1.92237056 1.98887407]
  [1.1284238  1.60085761 1.6952631  1.53560008 1.30681469]
  [1.53558819 1.47931185 1.57281311 1.05579446 1.236033  ]]

 [[1.61208693 1.83011894 1.75321107 1.18940325 1.10735371]
  [1.10370821 1.83028052 1.63549879 1.09997061 1.02991578]
  [1.84650939 1.10459215 1.23316721 1.86143709 1.11110789]]]
F
[[[ 25  25  25  75 100]
  [ 25  75  75  75  25]
  [ 75  75  75  25  25]]

 [[ 75  75  75  25  25]
  [ 25  75  75  25   0]
  [ 75  25  25  75  25]]]


#### 18. Bonus question: instead of using numbers (i.e. 0, 25, 50, 75, and 100), use string values  ("A", "B", "C", "D", and "E") to label the array elements. For the example above, the expected result is:

```python
[[[ 'D',  'D',  'D',  'B',  'D'],
[ 'D',  'D',  'B',  'B',  'B'],
[ 'D',  'B',  'D',  'D',  'D']],
[[ 'B',  'B',  'B',  'B',  'E'],
[ 'D',  'D',  'D',  'D',  'D'],
[ 'B',  'D',   'A',  'D', 'D']]]
```
**Note**: you don't have to use Numpy in this question.

In [ ]:
# your code here